### ISSUE TITLE
融合的问题

### ISSUE THREAD

**Issue by Liumomo30** [Linfeng-Tang/PSFusion#13]
感谢您在代码方面做出的贡献，红外和可见光图像必须要要有掩码图才能融合吗

**Comment by Linfeng-Tang** [comment]
在本文中 掩模只是在训练阶段用到 也有许多方法不需要使用掩模训练的 如SwinFusion SeAFusion 等

**Comment by Liumomo30** [comment]
感谢您的回复，但是由于拍摄过程中我的红外相机和可见光相机之间存在视差，两种图像存在一定偏移，应该如何解决呢，非常感谢您的耐心解答

**Comment by clw5180** [comment]
> 感谢您的回复，但是由于拍摄过程中我的红外相机和可见光相机之间存在视差，两种图像存在一定偏移，应该如何解决呢，非常感谢您的耐心解答

兄弟你是在搞gaiic吧

**Comment by Liumomo30** [comment]
> > 感谢您的回复，但是由于拍摄过程中我的红外相机和可见光相机之间存在视差，两种图像存在一定偏移，应该如何解决呢，非常感谢您的耐心解答
> 
> 兄弟你是在搞gaiic吧

兄弟，没有哈哈哈哈
