### ISSUE TITLE
Problem with downloading prertrained models from pan.baidu

### ISSUE THREAD

**Issue by Gazuz33** [Linfeng-Tang/PSFusion#5]
Hello dear Linfeng Tang. My problem is that I can’t download the checkpoint and dataset from the pan.baidu website. I would like to test your development. I would be very grateful if you could send these files to me at a4tonetak@gmail.com or upload these files to Google Disk.

**Comment by Linfeng-Tang** [comment]
The MSRS dataset  for training PSFusion:
 MSRS.zip
<https://drive.google.com/file/d/1tK0VAHyWWxlRueUsRkeLSHGzgseAE6O5/view?usp=drive_web>
The pre-trained model for testing PSFusion:
 best_model.pth
<https://drive.google.com/file/d/1EP8HXYi-WJRt0aFpckB_L9nfPhMNd-jI/view?usp=drive_web>
The pre-trained model for testing SegNext for MFNet:
 res_MFNet.zip
<https://drive.google.com/file/d/1b25R2eZ8tF7-L8J3eWEvyYCiafq-SNOf/view?usp=drive_web>
The pre-trained model for testing SegNext for MSRS:
 res_MSRS.zip
<https://drive.google.com/file/d/1KBqBi_jJvpZ2f-03loyc7Y8GU-_J6JwP/view?usp=drive_web>
The pre-trained model for testing SegFormer:
 res_MSRS.zip
<https://drive.google.com/file/d/1e8gYLmnssJw0hkxGBZoqY1QRqQY23qm0/view?usp=drive_web>
The pre-trained model for testing BANet:
 model_PSFusion.pth
<https://drive.google.com/file/d/1ZMwp_l0t_5pT2cmbq-act0T8q-vKJwHA/view?usp=drive_web>





Andrew Goncharov ***@***.***> 于2023年9月20日周三 20:50写道：

**Comment by Linfeng-Tang** [comment]
The MSRS and MFNet datasets for training SegFormer and SegNext:
 datasets.zip
<https://drive.google.com/file/d/1cXXMiNOJ46JgZ7p7MDHaTAJh2hA6lmM4/view?usp=drive_web>


Andrew Goncharov ***@***.***> 于2023年9月20日周三 20:50写道：

**Comment by Gazuz33** [comment]
Dear Linfeng Tang, thank you very much for your help
